### ISSUE TITLE
Support additional information or custom messages

### ISSUE THREAD

**Issue by sbacarob** [axelson/password-validator#15]
The line in the code that adds the errors to the changeset simply does:

```elixir
Ecto.Changeset.add_error(cset, field, error)
```

It would be nice if it were possible to take advantage of the options `Ecto.Changeset.add_error/4` supports as its fourth argument to pass additional information. Or to be able to define a custom message.

I have a use case where I want to validate not just if there are errors in the password field in general, but if there are errors generated by the validator. For which I'm pattern matching against `"Not enough" <> _` (as the project only checks for presence of numbers, symbols, etc.), but if at some point the message was to be changed by something else, or we were to set a max number of some type of characters, it would stop working, which is definitely not ideal.

I can also add more info to the errors that happen outside of `password-validator` and check for errors different from that, but I still think it would be ideal to have either of this options

**Comment by axelson** [comment]
Hi :wave:!

Thanks for the suggestions. I definitely think it makes sense to add some additional info using the `keys` keyword list. Pattern matching on `"Not enough" <> _` is obviously very brittle. I have to think a bit more on what an api for custom error messages would look like, but that does make sense as a feature request as well.

**Comment by sbacarob** [comment]
@axelson Thank you for addressing this so quickly!
