### ISSUE TITLE
Support NIST 5.1 requirements

### ISSUE THREAD

**Issue by axelson** [axelson/password-validator#4]
https://elixirforum.com/t/passwordvalidator-a-library-to-validate-common-password-rules-and-implement-your-own/19621/2?u=axelson

Maybe create it as some sort of preset?

**Comment by OvermindDL1** [comment]
Might be good as the 'Default' preset as well, but yep a preset is what I was thinking, it's what most places either do or should be following.  :-)

**Comment by axelson** [comment]
Realistically I'm not going to get to this, closing.
